openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
  description: A sample API to illustrate OpenAPI concepts
servers:
  - url: 'https://api.sample.com/v1'
paths:
  /items:
    get:
      summary: List all items
      responses:
        '200':
          description: A list of items
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int64
                    name:
                      type: string
                    price:
                      type: number
                      format: float
